### ISSUE TITLE
解析map嵌套结构体bug

### ISSUE THREAD

**Issue by willkk** [xyz347/xpack#11]
map的value类型是结构体，解析有问题。
示例：
```
struct value {
  int a;
  XPACK(O(a));
};
std::map<std::string, value>  map;
xpack::json::decode("{\"123\":{\"a\":1011}, \"234\":{}}", map);
cout << map.size() << ',' << map["123"].a << ',' << map["234"].a << endl;
```
后面空的234的a跟前面123里面的a值一样，看起来是内部实现复用了结构体成员。

**Comment by xyz347** [comment]
这是由于未初始化变量的随机性导致的。value加个构造函数value():a(0){}就可以看出来了

**Comment by willkk** [comment]
没懂，是使用方代码问题，还是xpack有问题？我理解，如果不提供构造函数，解析出来的int成员应该是随机值，但现在的结果是跟上一个对象的成员相同。这里的逻辑是不是有问题。

**Comment by xyz347** [comment]
应该说是一个巧合，比如这段代码在我电脑上跑，每次map["234"].a的值都是随机数。

**Comment by willkk** [comment]
好的，明白。
