### ISSUE TITLE
空数组出错

### ISSUE THREAD

**Issue by motopx** [xyz347/xpack#19]
json文本为：{"data":{"info":[]}}时，解析会出错。在document.h的IsArray出错。
struct Info
	{
		int base, Id;
		XPACK(O(base, Id));
	};
struct dataInfo
	{
		std::vector<Info> data;
		XPACK(O(data));
	};
dataInfo sInfo;
xpack::json::decode("{\"data\":{\"info\":[]}}", sInfo);

**Comment by xyz347** [comment]
你的data是{}，也就是object，然后结构体里面是vector，

**Comment by motopx** [comment]
"info":[]，"info":null，用xpack::JsonData info时，出提示尝试引用已删除的函数

**Comment by xyz347** [comment]
JsonData是noncopyable的，不允许复制（也就是不能return之类的），建议做法是std::shared_ptr<xpack::JsonData>这样
