### ISSUE TITLE
请问大佬，这种嵌套的坐标数组应该如何构建结构体

### ISSUE THREAD

**Issue by CasonTsai** [xyz347/xpack#22]
![image](https://user-images.githubusercontent.com/18262642/160520576-a1927180-a57d-4799-a92a-e46e8211e4cc.png)

**Comment by CasonTsai** [comment]
数组是不定长的

**Comment by xyz347** [comment]
嵌套vector：vector<vector<float>> 这样

**Comment by CasonTsai** [comment]
好的谢谢
