### ISSUE TITLE
customize basetype's serialisation

### ISSUE THREAD

**Issue by southern-dust** [xyz347/xpack#24]
Dear developer,
How could I do if I wanna to customize basetype's serialisation? For example, if I want to convert an int to its hex string representation during serialize or deserialize, current xtype.cpp cannot do this, its just warning "already defined" when I write template<int>.
Any suggestions well be welcome.

**Comment by xyz347** [comment]
Currently not supported, I think about how to achieve more appropriate

**Comment by xyz347** [comment]
see this [example](https://github.com/xyz347/xpack/blob/custom-codec/example/custom.cpp)
use 'C' to include members:C(xxx, flags, member1, member2....)
and implement xxx_decode and xxx_encode(in namespace of xpack)
