### ISSUE TITLE
enum class Enum : int64_t解析会出错

### ISSUE THREAD

**Issue by eddywuhu** [xyz347/xpack#25]
enum class Enum : int64_t  类型的枚举解析会出错，解析出来是个很大的值， 如果是enum class Enum : int 不会出错，是哪里的bug 吗

**Comment by eddywuhu** [comment]
enum class Enum : int64_t {
    X = 0,
    Y = 1,
    Z = 2,
};

struct Test {
    string  name;
    Enum    e;
    XPACK(O(name), E(F(0), e));
};
例子中解析会出错
string json="{\"name\":\"IPv4\", \"e\":1}";
xpack::json::decode(json, t);

**Comment by xyz347** [comment]
enum class是C++11才支持的写法，编译器支持C++11的时候，枚举不要用E来包含，直接用O就可以了。
XPACK(O(name, e));
这样写就可以。E是用于编译器不支持C++11的时候用的，这个时候枚举默认就是int类型

**Comment by xyz347** [comment]
已修正
