### ISSUE TITLE
float类型怎么限制位数

### ISSUE THREAD

**Issue by Eternity1987** [xyz347/xpack#30]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/15373993/196335326-c78af839-64ba-42fb-8179-5dc5c58cf6fe.png">

**Comment by xyz347** [comment]
目前不支持

**Comment by xyz347** [comment]
最新的代码增加SetMaxDecimalPlaces了这个函数，可以用来控制float的小数位数。例子：
``` C++
    xpack::JsonEncoder en(-1);
    en.SetMaxDecimalPlaces(3);
    en.encode(NULL, t, NULL);
    std::string s = en.String();
```
可以把这段代码封装成一个函数
