### ISSUE TITLE
能否支持字段自定义校验函数

### ISSUE THREAD

**Issue by xieepp** [xyz347/xpack#31]
字段从配置文件解析到结构体后，调用字段自定义校验函数
结构体解析完成后，调用结构体自定义校验函数

**Comment by xyz347** [comment]
这个可以通过自定义编解码实现，具体可以参考这个[例子](https://github.com/xyz347/xpack/blob/master/example/xtype_advance.cpp)

**Comment by xieepp** [comment]
基于XTOSTRUCT_OUT实现测试通过了：
//V:对成员变量校验
//U:成员解析校验完成后，对结构体进行校验
struct Employee
{
    string name;
    int     age;
    string   title;
};
XTOSTRUCT_OUT(Employee,
    V(title, [](string& val) {return !val.empty() && val.length() < 16; }),
    V(name, [](string& val) {return !val.empty() && val.length() < 32; }),          
    V(age, [](int& val) {if (val < 18) val = 18; return true; }),                  
    U(Employee, [](Employee& val) {printf("Validator Employee\n"); return true; }));

**Comment by xyz347** [comment]
如果需要每个变量decode的时候都校验实现起来会复杂一些，如果只做对结构体校验那就比较简单
```C++
namespace xpack {

template<>
struct is_xpack_xtype<Employee> {static bool const value = true;};

template <class OBJ>
bool xpack_xtype_decode(OBJ& obj, const char *name, Employee &data, const xpack::Extend *ext) {
    (void)name;
    data.__x_pack_decode(obj, data, ext);
    // 对data进行校验
    return true;
}

}
```

**Comment by xieepp** [comment]
这么测试的：
`#define X_STRUCT_ACT_TOX_V(M, ...)                                          \
    {                                                                       \
        if (obj.convert(#M, X_SELF->M)) {                                   \
            if (obj.set_has()) __x_has_string.insert(#M);                   \
        }                                                                   \
        auto F = __VA_ARGS__;                                               \
        if (!F(X_SELF->M))                                                  \
            obj.md_exception(#M " Validate failed.");                       \
    }

#define X_STRUCT_ACT_TOX_U(M, ...)                                          \
    {                                                                       \
        auto F = __VA_ARGS__;                                               \
        if (!F(*X_SELF))                                                    \
            obj.md_exception(#M " Validate failed.");                       \
    }`

**Comment by xieepp** [comment]
会支持吗？不支持的话，我们另想办法了

**Comment by xieepp** [comment]
会支持吗？不支持的话，我另想办法了

**Comment by xyz347** [comment]
不支持。x2struct不会再维护了，如果是xpack，建议用xtype的方式来

**Comment by xieepp** [comment]
好的。
