### ISSUE TITLE
union支持情况

### ISSUE THREAD

**Issue by fresh-ji** [xyz347/xpack#33]
您好 请问XPACK是否支持union类型变量 如果不支持 有什么替代解决方案 非常感谢

**Comment by xyz347** [comment]
通过xtype可以支持，不过稍微复杂些，等我写了例子发出来

**Comment by fresh-ji** [comment]
感谢感谢！！！

**Comment by xyz347** [comment]
参考这个[例子](https://github.com/xyz347/xpack/blob/master/example/union1.cpp)
