### ISSUE TITLE
这个XPACK(A(1,a_1),A(2,a_2))里面的A()有映射个数限制么， 好像加到某个值之后，编译都是报错了

### ISSUE THREAD

**Issue by Eternity1987** [xyz347/xpack#35]

**Comment by xyz347** [comment]
25个，如果变量太多，可以放多个A

**Comment by Eternity1987** [comment]
多个A最多是99个是吧。我是每个A里放一个， 那总的最多99*25 是吧
![image](https://user-images.githubusercontent.com/15373993/206385257-ff7b7e5a-22fa-4eab-8de7-2ea5104a0f16.png)

**Comment by xyz347** [comment]
对的

**Comment by Eternity1987** [comment]
那写在一个A里 和多个A 对效率会有影响么

**Comment by xyz347** [comment]
没区别

**Comment by Eternity1987** [comment]
好的。感谢 good job
