### ISSUE TITLE
int64_t encode 结果有问题

### ISSUE THREAD

**Issue by ouxianghui** [xyz347/xpack#4]
struct JanusResponse {
		std::string janus;
		std::string transaction;		
		int64_t session_id = -1;
		int64_t sender = -1;
		XPACK(O(janus, transaction, session_id, sender));
	};
	
	struct CreateSessionData {
		int64_t id;
		XPACK(O(id));
	};

	struct CreateSessionResponse : public JanusResponse {
		CreateSessionData data;
		XPACK(I(JanusResponse), O(data));
	};

	std::string js = "{\"janus\":\"success\",\"transaction\":\"RftQMdXKkq6q\",\"data\":{\"id\":6053426257610390}}";
	vi::CreateSessionResponse model;
	xpack::json::decode(js, model);

	std::string result = xpack::json::encode(model);
	
	你好，我发现decode结果是对的，encode的结果是错的，id的值不对。是我的用法不对？
	（在x2struct上能正确encode）

**Comment by xyz347** [comment]
我跑了一下是OK的，你的输出是？

**Comment by ouxianghui** [comment]
我的输出是：str = "{\"janus\":\"success\",\"transaction\":\"RftQMdXKkq6q\",\"data\":{\"id\":566380182}}"
如果把 6053426257610390 改成一个比较小的数，比如6位数，结果是正确的。
我的环境：VS2017 x64 debug
