### ISSUE TITLE
windows下Qt + MSVC报以下错误：use of undeclared identifier 'X_PACK_L1_ENCODE'

### ISSUE THREAD

**Issue by liuly123** [xyz347/xpack#42]
在pro里加了include(xpack-1.0.5/xpack.pri)，
在linux下正常工作，
windows下Qt + MSVC，报以下错误：use of undeclared identifier 'X_PACK_L1_ENCODE'
另外，#include "xpack/xpack.h"不识别，#include "xpack.h"才行

**Comment by liuly123** [comment]
但是window下也能正常编译运行，只是编辑器报错

**Comment by xyz347** [comment]
这个属于编辑器的解析器问题
