### ISSUE TITLE
demo能运行,但是复制xml.cpp到项目中XPACK提示use of undeclared identifier NULL

### ISSUE THREAD

**Issue by lief93** [xyz347/xpack#43]
新建项目是可以运行的,但是在旧项目中就提示use of undeclared identifier NULL.请问是什么原因呢,另外demo中有ATTR的用法吗,找了下没找到,ATTR是只支持encode不支持decode吗
环境:ubuntu22.01
工具:clion

**Comment by xyz347** [comment]
不支持NULL应该是编译器版本的问题，你可以参考一下[这个](https://stackoverflow.com/questions/924664/why-is-null-undeclared)
ATTR支持encode和decode，可以看[这里](https://github.com/xyz347/xpack/blob/master/gtest/test.cpp#L73)
