### ISSUE TITLE
 return-statement with a value, in function returning ‘void’

### ISSUE THREAD

**Issue by zhaoyang73** [xyz347/xpack#45]
json.h:39:82: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
   39 |         return XDecoder<JsonNode>(NULL, (const char*)NULL, node).decode(val, NULL);

there is a error of json.h，
![image](https://github.com/xyz347/xpack/assets/141006574/fd01a6dc-05d9-468c-99dc-05ea4ee5005b)
the template function return a bool value, but the description of function return void.

**Comment by xyz347** [comment]
fixed
