### ISSUE TITLE
xml解析

### ISSUE THREAD

**Issue by lining1111** [xyz347/xpack#48]
你好，请问以下xml节点，结构体的XPACK怎么写
 <apply>
       <url target="节目组织XML中的文件名1">文件1网址base64加密</url>
       <url target="节目组织XML中的文件名2">文件2网址base64加密</url>
 <apply/>

注：url是数组成员，带attr，但内容是直接给节点的

**Comment by xyz347** [comment]
?

**Comment by lining1111** [comment]
不好意思，应该是网页把xml的标记屏蔽了，下面是xml的截图
![1716335182194](https://github.com/xyz347/xpack/assets/17841935/4c1bf383-9ecf-4dd2-85f5-3def4cdea1d4)
用结构体描述就是
class Item{
public:
    string name;
    string value;
XPACK(X(F(ATTR),name), O(value));
};
class Node {
public:
    string type;
    string name;
    vector<Item> url;
XPACK(O(name), X(F(ATTR), type),A(url,"xml:url,sbs"));
};
![Uploading 1716335598910.png…]()

上面的Node类如果形成截图中的apply节点的话，url会是数组，但是数组的成员会是这样的
就是Item中的value不会以pcdata的形式出现，会以url下value节点的值形式出现

**Comment by lining1111** [comment]
上面的第二个图不知道上传出现什么问题了，您看下我的结构体中的XPACK约束应该就是能看出我的XPACK约束达不到第一个截图的效果

**Comment by xyz347** [comment]
这个功能目前还没支持，因为存在一个target变量，因此整行需要时候一个结构体，但是里面的内容没有变量来接收（匿名了）

**Comment by xyz347** [comment]
支持了，参考例子 https://github.com/xyz347/xpack/blob/master/example/xml-content.cpp
