### ISSUE TITLE
XPACK_OUT解析过大结构体时出现段错误

### ISSUE THREAD

**Issue by pursuerbxh** [xyz347/xpack#51]
目前是将xpack的解析json功能用于构造测试用例。代码中有一个结构体比较大，有3892616byte，在执行用例的时候出现了段错误。尝试减少结构体成员个数，发现3568232byte可以正常运行，但是目前不知道明确的边界。
这个结构体之前在ut测试中一直存在，区别只是第一次将其放到了json文件中，所以怀疑是不是xpack哪个地方产生了对结构体大小的限制。

**Comment by xyz347** [comment]
xpack没有对内存进行限制，段错误看看是不是因为内存不足导致的。

**Comment by pursuerbxh** [comment]
> xpack没有对内存进行限制，段错误看看是不是因为内存不足导致的。

好的，非常感谢。刚发现是ut的类模板有问题，之前是因为xpack的代码比较难读，所以想先来这边确认一下。打扰到了请见谅
