### ISSUE TITLE
继承的Struct进行encode时，父结构体的json键值对出现两次

### ISSUE THREAD

**Issue by TaoWang-87** [xyz347/xpack#52]
struct Base; 
Struct Derived : public Base;

对Derived进行encode并输出json， 结果是Base的键值对在json中出现两次

**Comment by xyz347** [comment]
方便贴一下测试代码吗？

**Comment by TaoWang-87** [comment]
Sorry, 误报。 

又做了测试脚本，测试了一把，没问题。
后面复查，发现是Derived的XPACK把 Base的内容带进去了。

关闭此问题。
